### ISSUE TITLE
Add pdf-view-mode

### ISSUE THREAD

**Issue by jockej** [mattfidler/linum-off#1]
Hi, thanks for this package!

I just thought you could add pdf-view-mode to the default off modes. I know I could add it myself, but I think the beauty of this mode is that it Does The Right Thing without having to customize stuff. And there is definitely no way anybody would want linum-mode enabled in pdf-view-mode.

Just a suggestion :)

**Comment by mattfidler** [comment]
Thats true.  You could also add it yourself to github.  Its quite easy, you don't even need to clone the repository.  Anyhow its done.
